[package]
name = "mtpng"
version = "0.1.0"
authors = ["Brion Vibber <brion@pobox.com>"]

[dependencies]
rayon = "1.0.2"
crc = "1.8.1"
libz-sys = "1.0.20"
png = "0.12.0"
clap = "2.32.0"
time = "0.1.40"
itertools = "0.7.8"
libc = "0.2.43"
typenum = "1.10.0"

[lib]
crate-type = ["rlib", "cdylib"]

[profile.release]
# Unoptimized debug builds are too slow to profile
# having debug info doesn't hurt perf for now
debug = true
